# Generated by Django 6.1.1 on 2026-09-07 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('category', models.CharField(choices=[('workout', 'Workout'), ('nutrition', 'Nutrition'), ('general', 'General')], default='general', max_length=10)),
                ('url', models.URLField()),
                ('source', models.CharField(blank=True, help_text="e.g. 'Healthline', 'NASM'", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]