# Generated by Django 6.1 on 2026-08-23 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('report_type', models.CharField(choices=[('short', 'Short'), ('detailed', 'Detailed')], default='short', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('progress_summary', models.TextField(blank=True)),
                ('workout_feedback', models.TextField(blank=True)),
                ('nutrition_feedback', models.TextField(blank=True)),
                ('key_takeaways', models.TextField(blank=True)),
                ('rule_based_insights', models.JSONField(blank=True, default=dict)),
                ('generation_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProgressReportSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_interval', models.PositiveSmallIntegerField(default=7)),
                ('report_type', models.CharField(choices=[('short', 'Short'), ('detailed', 'Detailed')], default='short', max_length=10)),
                ('is_enabled', models.BooleanField(default=True)),
                ('last_generated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
