# Generated by Django 6.1.1 on 2026-09-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='triggered_by',
            field=models.CharField(choices=[('manual', 'Manual'), ('interval', 'Interval')], default='manual', max_length=10),
        ),
        migrations.AlterField(
            model_name='progressreportsettings',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Whether interval-based (automatic) report generation is allowed.'),
        ),
    ]