# Generated by Django 6.1.1 on 2026-09-03 12:09

from django.conf import settings
from django.db import migrations, models


def backfill_report_numbers(apps, schema_editor):
    """The AddField above gives every existing row report_number=1 as a
    placeholder default -- if any user already has more than one report,
    that violates the UniqueConstraint added right after this runs. Renumber
    each user's existing reports 1, 2, 3... in creation order before that
    constraint is added."""
    ProgressReport = apps.get_model("progress", "ProgressReport")
    user_ids = ProgressReport.objects.order_by().values_list("user_id", flat=True).distinct()
    for user_id in user_ids:
        reports = ProgressReport.objects.filter(user_id=user_id).order_by("created_at", "id")
        for index, report in enumerate(reports, start=1):
            if report.report_number != index:
                report.report_number = index
                report.save(update_fields=["report_number"])


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0002_progressreport_triggered_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='report_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(backfill_report_numbers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='progressreport',
            constraint=models.UniqueConstraint(fields=('user', 'report_number'), name='unique_report_number_per_user'),
        ),
    ]