# Generated by Django 6.1.1 on 2026-09-05 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_progressreport_report_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreportsettings',
            name='generation_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]