# Generated by Django 6.1.1 on 2026-10-01 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0004_progressreportsettings_generation_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressreportsettings',
            name='day_interval',
            field=models.PositiveSmallIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
