# Generated by Django 6.1 on 2026-08-22 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('local_name', models.CharField(blank=True, help_text='Filipino/regional name if different', max_length=200)),
                ('category', models.CharField(choices=[('rice_grains', 'Rice & Grains'), ('viands_meat', 'Viands - Meat & Poultry'), ('viands_fish', 'Viands - Fish & Seafood'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('soups', 'Soups & Stews'), ('snacks', 'Snacks & Merienda'), ('desserts', 'Desserts & Sweets'), ('beverages', 'Beverages'), ('condiments', 'Condiments & Sauces'), ('other', 'Other')], max_length=20)),
                ('serving_description', models.CharField(help_text="e.g. '1 cup cooked', '1 piece (medium)', '100g'", max_length=100)),
                ('serving_size_g', models.FloatField(help_text='Edible portion weight in grams')),
                ('calories', models.FloatField(help_text='kcal per serving_description')),
                ('protein_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('fiber_g', models.FloatField(blank=True, null=True)),
                ('sodium_mg', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(default='PhilFCT (cross-referenced)', help_text="Data provenance, e.g. 'PhilFCT 2019', 'FNRI FOI request', 'estimated'", max_length=100)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='nutrition_f_name_cad16d_idx')],
            },
        ),
        migrations.CreateModel(
            name='FoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], max_length=10)),
                ('servings', models.FloatField(default=1.0)),
                ('calories', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('fat_g', models.FloatField()),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('daily_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_entries', to='nutrition.dailyentry')),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.fooditem')),
            ],
        ),
        migrations.CreateModel(
            name='NutritionProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_calories_goal', models.FloatField(default=2000)),
                ('daily_protein_goal', models.FloatField(default=100)),
                ('daily_carbs_goal', models.FloatField(default=250)),
                ('daily_fat_goal', models.FloatField(default=65)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dailyentry',
            name='nutrition_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to='nutrition.nutritionprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='dailyentry',
            unique_together={('nutrition_profile', 'date')},
        ),
    ]
