# Generated by Django 6.1 on 2026-08-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, help_text="Source dataset's own ID (e.g. PhilFCT Food_ID like 'A001'), for idempotent bulk imports", max_length=20),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('rice_grains', 'Rice & Grains'), ('roots_tubers', 'Starchy Roots & Tubers'), ('nuts_legumes', 'Nuts, Legumes & Seeds'), ('viands_meat', 'Viands - Meat & Poultry'), ('viands_fish', 'Viands - Fish & Seafood'), ('eggs', 'Eggs'), ('dairy', 'Milk & Dairy'), ('fats_oils', 'Fats & Oils'), ('vegetables', 'Vegetables'), ('fruits', 'Fruits'), ('soups', 'Soups & Stews'), ('snacks', 'Snacks & Merienda'), ('desserts', 'Desserts & Sweets'), ('beverages', 'Beverages'), ('condiments', 'Condiments & Sauces'), ('other', 'Other')], max_length=20),
        ),
    ]
