# Generated by Django 6.1 on 2026-08-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_fooditem_external_id_alter_fooditem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='search_text',
            field=models.TextField(blank=True, help_text='Extra searchable terms (scientific name, alt spellings) not shown in the UI'),
        ),
    ]
