# Generated by Django 6.1.1 on 2026-09-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_fooditem_search_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritionprofile',
            name='auto_recalculate_goals',
            field=models.BooleanField(default=True),
        ),
    ]
