# Generated by Django 6.1 on 2026-08-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Used to calculate age for calorie/macro goal suggestions', null=True),
        ),
    ]
