# Generated by Django 6.1.1 on 2026-09-03 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_experience_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='experience_level',
        ),
    ]