# Generated by Django 6.1.1 on 2026-09-16 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_weightlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unit_system',
            field=models.CharField(choices=[('metric', 'Metric (kg, cm)'), ('imperial', 'Imperial (lbs, ft/in)')], default='metric', max_length=10),
        ),
    ]
