# Generated by Django 6.1.1 on 2026-09-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_height_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
