# Generated by Django 6.1.1 on 2026-09-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='verification_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='verification_code_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='verification_code_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
