# Generated by Django 6.1 on 2026-08-24 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WgerExercise',
            fields=[
                ('id', models.IntegerField(help_text="wger's exercise base_id", primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('equipment_name', models.CharField(blank=True, max_length=200)),
                ('muscle_names', models.CharField(blank=True, max_length=300)),
                ('synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='workouts_wg_name_132e01_idx')],
            },
        ),
    ]
