# Generated by Django 6.1 on 2026-08-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_wgerexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatehistory',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]