# Generated by Django 6.1 on 2026-08-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_templatehistory_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='performedexercise',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2),
        ),
        migrations.AddField(
            model_name='templateexercise',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2),
        ),
    ]