# Generated by Django 6.1 on 2026-09-02 01:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_performedexercise_weight_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttemplate',
            name='day_type',
            field=models.CharField(blank=True, choices=[('full_body', 'Full Body'), ('upper', 'Upper Body'), ('lower', 'Lower Body'), ('push', 'Push'), ('pull', 'Pull'), ('legs', 'Legs')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='workouttemplate',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='workouttemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('is_generated', True)), fields=('user', 'day_type'), name='one_generated_template_per_day_type_per_user'),
        ),
    ]