# Generated by Django 6.1.1 on 2026-09-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_workoutgenerationstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutgenerationstate',
            name='generated_for_frequency',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workoutgenerationstate',
            name='generated_for_goal',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='workoutgenerationstate',
            name='generated_for_location',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
